name: CI

on:
  push:
    branches: master

jobs:
  test:
    name: test w/ Python ${{ matrix.python-version }}

    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install nox
      - run: nox --session tests-${{ matrix.python-version }}
        env:
          PYTHONDEVMODE: 1
      - uses: codecov/codecov-action@v1
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cov.xml
